version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-email
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP port for connections
      - "15672:15672" # Management UI port
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge